name: clean_architecture_tdd
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# Service locator
  get_it: ^3.0.3
# Bloc for flutter
  flutter_bloc: ^2.1.1

  equatable: ^1.0.1

  dartz: ^0.8.9

  data_connection_checker: ^0.3.4
  http: ^0.12.0+2

  shared_preferences: ^0.5.3+4

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:

  uses-material-design: true

